language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t noopurphalak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true noopurphalak/docker-react npm run test